### ISSUE TITLE
Feature request Image dimensions / border

### ISSUE THREAD

**Issue by bkdotcom** [tomek-f/chrome-image-transparency#1]
An option to draw a border around the image would beneficial
and/or a solid background color outside the img
(a visual indication of where the image's canvas is / ends)

As the background is transparent, there's currently no way to tell where the right & bottom image boundary is

**Comment by tomek-f** [comment]
![new-chrome](https://cloud.githubusercontent.com/assets/1083258/23092155/147ca06c-f5c5-11e6-931d-018590e2fb0f.png)

Whole extesnsion is kinda useless now ;)

**Comment by bkdotcom** [comment]
how so?
it now shows transparency AND bounding box

**Comment by tomek-f** [comment]
What you see on teh screen is Chrome default behavior. Black background around image. Image with grid background to show transparency.
My extension is useless now, doesn't work at the moment.

**Comment by tomek-f** [comment]
New fixed version out. Working from chrome 56.

**Comment by bkdotcom** [comment]
strange coincidence
thanks!
